import mongoose from "mongoose";

const documentSchema = new mongoose.Schema(
  {
    aadhaarCard: { type: String, default: "" },
    panCard: { type: String, default: "" },
    passport: { type: String, default: "" },
    drivingLicence: { type: String, default: "" },
    communityCertificate: { type: String, default: "" },
    transferCertificate: { type: String, default: "" },
    migrationCertificate: { type: String, default: "" },
    birthCertificate: { type: String, default: "" },
  },
  { _id: false }
);

const userSchema = new mongoose.Schema(
  {
    name: { type: String, required: true, trim: true },
    email: { type: String, required: true, unique: true, lowercase: true, trim: true },
    password: { type: String, required: true },
    role: {
      type: String,
      enum: ["superadmin", "admin", "staff", "student"],
      required: true,
    },
    isActive: { type: Boolean, default: false },
    permissions: { type: [String], default: [] },
    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
    studentProfile: {
      studentId: { type: String, default: "", trim: true },
      firstName: { type: String, default: "", trim: true },
      middleName: { type: String, default: "", trim: true },
      lastName: { type: String, default: "", trim: true },
      dateOfBirth: { type: Date, default: null },
      gender: { type: String, enum: ["male", "female", "other", ""], default: "" },
      bloodGroup: { type: String, default: "", trim: true },
      nationality: { type: String, default: "", trim: true },
      aadhaarPassportNumber: { type: String, default: "", trim: true },
      profilePhoto: { type: String, default: "" },
      mobileNumber: { type: String, default: "", trim: true },
      alternateMobileNumber: { type: String, default: "", trim: true },
      parentGuardianMobile: { type: String, default: "", trim: true },
      parentGuardianEmail: { type: String, default: "", trim: true },
      addressLine1: { type: String, default: "", trim: true },
      addressLine2: { type: String, default: "", trim: true },
      city: { type: String, default: "", trim: true },
      district: { type: String, default: "", trim: true },
      state: { type: String, default: "", trim: true },
      country: { type: String, default: "", trim: true },
      pincode: { type: String, default: "", trim: true },
      fatherName: { type: String, default: "", trim: true },
      fatherOccupation: { type: String, default: "", trim: true },
      motherName: { type: String, default: "", trim: true },
      motherOccupation: { type: String, default: "", trim: true },
      guardianName: { type: String, default: "", trim: true },
      guardianRelationship: { type: String, default: "", trim: true },
      annualFamilyIncome: { type: String, default: "", trim: true },
      schoolCollegeName: { type: String, default: "", trim: true },
      previousQualification: { type: String, default: "", trim: true },
      boardUniversity: { type: String, default: "", trim: true },
      yearOfPassing: { type: String, default: "", trim: true },
      percentageCgpa: { type: String, default: "", trim: true },
      mediumOfInstruction: { type: String, default: "", trim: true },
      course: { type: String, default: "", trim: true },
      batch: { type: String, default: "", trim: true },
      branchCampus: { type: String, default: "", trim: true },
      section: { type: String, default: "", trim: true },
      admissionDate: { type: Date, default: null },
      modeOfLearning: { type: String, enum: ["online", "offline", "hybrid", ""], default: "" },
      duration: { type: String, default: "", trim: true },
      expectedCompletionDate: { type: Date, default: null },
      documents: { type: documentSchema, default: () => ({}) },
      emergencyContactName: { type: String, default: "", trim: true },
      emergencyContactRelationship: { type: String, default: "", trim: true },
      emergencyContactMobile: { type: String, default: "", trim: true },
      emergencyContactAlternate: { type: String, default: "", trim: true },
      username: { type: String, default: "", trim: true },
      registrationFee: { type: String, default: "", trim: true },
      courseFee: { type: String, default: "", trim: true },
      scholarship: { type: String, default: "", trim: true },
      discount: { type: String, default: "", trim: true },
      paymentMethod: { type: String, default: "", trim: true },
      paymentStatus: { type: String, default: "", trim: true },
      transactionId: { type: String, default: "", trim: true },
      receiptNumber: { type: String, default: "", trim: true },
      medicalConditions: { type: String, default: "", trim: true },
      allergies: { type: String, default: "", trim: true },
      disabilities: { type: String, default: "", trim: true },
      emergencyNotes: { type: String, default: "", trim: true },
      languagesKnown: { type: String, default: "", trim: true },
      computerSkills: { type: String, default: "", trim: true },
      careerGoal: { type: String, default: "", trim: true },
      preferredCommunicationLanguage: { type: String, default: "", trim: true },
      termsAccepted: { type: Boolean, default: false },
      privacyAccepted: { type: Boolean, default: false },
      studentSignature: { type: String, default: "", trim: true },
      parentSignature: { type: String, default: "", trim: true },
      declarationDate: { type: Date, default: null },
    },
  },
  { timestamps: true }
);

userSchema.index({ role: 1, createdAt: -1 });
userSchema.index({ "studentProfile.studentId": 1 }, { unique: true, sparse: true });

export default mongoose.model("User", userSchema);
